using System.Collections.Generic;

namespace Wikiled.IB.Market.Api.Client
{
    /**
     * @class CommissionReport
     * @brief class representing the commissions generated by an execution.
     * @sa Execution
     */
    public class CommissionReport
    {
        public CommissionReport()
        {
            Commission = 0;
            RealizedPnl = 0;
            Yield = 0;
            YieldRedemptionDate = 0;
        }

        /**
        * @brief the execution's id this commission belongs to.
        */
        public string ExecId { get; set; }

        /**
         * @brief the commissions cost.
         */
        public double Commission { get; set; }

        /**
        * @brief the reporting currency.
        */
        public string Currency { get; set; }

        /**
        * @brief the realized profit and loss
        */
        public double RealizedPnl { get; set; }

        /**
         * @brief The income return.
         */
        public double Yield { get; set; }

        /**
         * @brief date expressed in yyyymmdd format.
         */
        public int YieldRedemptionDate { get; set; }

        public override bool Equals(object pOther)
        {
            var retVal = false;

            if (pOther == null)
            {
                retVal = false;
            }
            else if (this == pOther)
            {
                retVal = true;
            }
            else
            {
                var other = (CommissionReport)pOther;
                retVal = ExecId.Equals(other.ExecId);
            }

            return retVal;
        }

        public override int GetHashCode()
        {
            var hashCode = -2052112293;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(ExecId);
            hashCode = hashCode * -1521134295 + Commission.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Currency);
            hashCode = hashCode * -1521134295 + RealizedPnl.GetHashCode();
            hashCode = hashCode * -1521134295 + Yield.GetHashCode();
            hashCode = hashCode * -1521134295 + YieldRedemptionDate.GetHashCode();
            return hashCode;
        }
    }
}