namespace Wikiled.IB.Market.Api.Client
{
    /**
     * @class CommissionReport
     * @brief class representing the commissions generated by an execution.
     * @sa Execution
     */
    public class CommissionReport
    {
        public CommissionReport()
        {
            Commission = 0;
            RealizedPnl = 0;
            Yield = 0;
            YieldRedemptionDate = 0;
        }

        /**
        * @brief the execution's id this commission belongs to.
        */
        public string ExecId { get; set; }

        /**
         * @brief the commissions cost.
         */
        public double Commission { get; set; }

        /**
        * @brief the reporting currency.
        */
        public string Currency { get; set; }

        /**
        * @brief the realized profit and loss
        */
        public double RealizedPnl { get; set; }

        /**
         * @brief The income return.
         */
        public double Yield { get; set; }

        /**
         * @brief date expressed in yyyymmdd format.
         */
        public int YieldRedemptionDate { get; set; }

        protected bool Equals(CommissionReport other)
        {
            return ExecId == other.ExecId;
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != GetType())
            {
                return false;
            }

            return Equals((CommissionReport) obj);
        }

        public override int GetHashCode()
        {
            return ExecId != null ? ExecId.GetHashCode() : 0;
        }
    }
}